### PR TITLE
export data symbols

### PR DESCRIPTION
**Pull request by k-dominik**
Hey @hmaarrfk,

this is intended for your information. It doesn't work yet. While this compiles fine, the test exits with `Exit code 0xc0000135`, which means that the `lemon.dll` cannot be found. I have confirmed that it is in fact build, but I don't understand why it is not found.

Don't know if I will have more time on the weekend to work on it.

### CODE REVIEW

**Comment by k-dominik** [comment]
if I add

```cmd
set PATH=lemon/Release;%PATH%
```

in `bld.bat` before calling `ctest -R ...` it works, but this looks super hacky. An alternative would be to copy the dll to the test folder via cmake somehow, but this also feels hacky.

**Comment by k-dominik** [comment]
looks like it's not a completely hacky idea after all...

i checked `test/CMakeLists.txt` and it's copying other shared libraries to the test folder, too:

https://github.com/k-dominik/lemon/blob/cd048885e1e3539d533febf1f54d0fc2b3ade56a/test/CMakeLists.txt#L88-L92

some more digging led me to this wonderful advice: https://stackoverflow.com/a/59594095 :pray: 

I added a patch accordingly that copies `lemon.dll` to the tests' output folder(s) if not already present.
The one test we run passes :tada:

**Comment by k-dominik** [comment]
okay, hang on, my last (meant to be cleaned up) force-push broke it again

**Comment by k-dominik** [comment]
back on track! This is ready to be reviewed/merged :)

**Comment by hmaarrfk** [comment]
much fun!

**Pull request merged**
